//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sys_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub user_id: i32,
    #[sea_orm(unique)]
    pub username: String,
    pub password_hash: String,
    pub real_name: Option<String>,
    #[sea_orm(unique)]
    pub email: Option<String>,
    pub phone: Option<String>,
    pub avatar: Option<String>,
    pub status: i16,
    pub last_login_time: Option<DateTime>,
    pub last_login_ip: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub remark: Option<String>,
    pub create_by: Option<String>,
    pub create_time: DateTime,
    pub update_by: Option<String>,
    pub update_time: Option<DateTime>,
    pub is_deleted: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
